### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by mikeal** [iojs/iojs-ja#1]
Welcome, new localizations team :)

To get this team up and running you have a few initial tasks to accomplish:
- Create a README.md for this repository, it should include:
  - A "call to action" pointing to the Issue tracker for new translators to find tasks.
  - A list of the team members.
  - Instructions on how to log an issue to be added to this team.
- Set the repository description. This should not be in English, it should be in the language for this community :)
- Social Media
  - Create a twitter account for this language. Share the password privately with the team.
  - Create accounts on other social media popular in this language. Share the passwords private with the rest of the team.
  - Make sure you use these accounts not just to promote newly translated material but also to attract people in your community to help with translation tasks.
- _Optional:_ If you plan to do a Google hangout w/ your localization team have @mikeal add you to the Google+ account so that it can post to the `iojs` YouTube channel. Once you are added there is [documentation on how to setup a hangout-on-air](https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event).
- Finally, create a new Issue to translate and publish the [latest io.js post](https://medium.com/@iojs). Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.

**Comment by shinnn** [comment]
Added the readme. 6d239a58d086aabf6bf0a6372f45848892377d4e

**Comment by shinnn** [comment]
Created the twitter account. https://twitter.com/iojs_jp

**Comment by martinheidegger** [comment]
Just small question: jp is the code for "japan" ... "ja" would be for "japanese" right?

**Comment by nulltask** [comment]
@martinheidegger You're right! :+1:

"jp" is country code and "ja" is language code. I think "ja" is more appropriate.

**Comment by okuryu** [comment]
@martinheidegger @nulltask Yeah, @mikeal is creating repositories to be confused the language with region.

**Comment by mikeal** [comment]
whoops! I'll rename :)

**Comment by mikeal** [comment]
renamed :)

**Comment by nulltask** [comment]
@mikeal :+1:

**Comment by watilde** [comment]
Wow, one year has already passed from this big leap! I'm happy to see the current comfortable situation :)

I will close this issue as resolved, and miss it. Thanks!
