### ISSUE TITLE
Update next-nightly 

### ISSUE THREAD

**Issue by yosuke-furukawa** [iojs/iojs-ja#105]
next nightly 用のリンクが追加されてますね。
https://github.com/nodejs/iojs.org/commit/8fdce5ade45903e5f347f790771d6027432071dc

**Comment by kohei-takata** [comment]
以下の変更も反映した上で、対応を行います。
https://github.com/nodejs/iojs.org/commit/503b87512747a28265d00536b297cdfaabd4bda0

**Comment by tgfjt** [comment]
merge済ということで。
