### ISSUE TITLE
Node.js に関する翻訳のサポートについて

### ISSUE THREAD

**Issue by watilde** [iojs/iojs-ja#118]
NodeSchoolのworkshopperの翻訳を行った際に、レビュー依頼をどこで募ればいいか分からなく、現状は直接それっぽい人にpingしてなんとか乗り切っています。
+ https://github.com/stevekane/promise-it-wont-hurt/pull/115
+ https://github.com/workshopper/how-to-npm/pull/79
+ https://github.com/maxogden/elementary-electron/pull/24

そして、フローをそろそろ持っても良いんじゃないかという話がnodeschool orgsで出ています。
+ https://github.com/nodeschool/organizers/issues/183
+ https://github.com/nodeschool/discussions/issues/2030

せっかくJapanese localization Working GroupがこうしてNode.js Community内にあるので、Node.js に直接関連した文章の翻訳やそのレビューを行っている人を`nodejs-ja`にもっと追加して、レビューの依頼をこのリポジトリー経由で可能にしてはどうかと思いました。いかがでしょう？

Refs: https://nodejs.org/en/about/working-groups/#i18n

**Comment by hiroppy** [comment]
日本の多くの人に目が止まるとこで今こういう翻訳やっているということがわかればいいなぁと思いました。 それによって協力してくださる方も増えるかもですし自分はこのリポジトリ経由にするのはありだと思います。

**Comment by tdtsh** [comment]
Martin に勧められて、たまにワークショッパーを翻訳している者です。node school (OSAKA) に参加した時とかに翻訳してます。進みが遅いせいもあって、誰かが同じ事をやっていないか確認できると嬉しいので、○○の翻訳はじめました的な宣言があっても良いかなと思いました。（以前翻訳が被っってしまった経験あります）

**Comment by yosuke-furukawa** [comment]
こういうのって今始まった話じゃないんですよ、結構色んな所で同じような試みやられてて失敗してるんですよね。
例えば英語から日本語に翻訳する enja-oss とかいうコミュニティもあって、そういうのも失敗してるんですよね。

https://github.com/enja-oss

基本的には「OSSの自治体制はそのOSS organizationを超えられないんじゃないか」、と思っていて、僕らが今やろうとしてるのってそのorganizationを超えて翻訳レビューをしてその品質を保つみたいな活動ですよね？

node organizationに関することをnodejs-jaが責任範囲として翻訳とレビューをするのは賛成なんだけど、nodejs-jaが積極的にやらなくても良いことはそのorganizationの中でやったほうがいいのではないかと思ってる。

今回の例で言うと nodeschoolのorganizationの中で今翻訳していますっていう話をしながら解決する方がいいと思う。

今こういう翻訳やってます、という宣言もそのOrganizationの中のが目が止まりやすいんじゃないでしょうか。

**Comment by watilde** [comment]
i18n WG の Responsibilities として `Node.js のコミュニティに関連しうるものの翻訳` とあるので、やはりNodeSchool に関する翻訳も、このWGが積極的にサポートするべきスコープの中にあるように思います。
> Translating any Node.js materials they believe are relevant to their community.

関連して、 Tracy が動いている [International Contribution Day](https://github.com/nodeschool/organizers/issues/422) では、nodeschool, nodejs, workshopper の3つの org を横断して NodeSchool の活性化をサポートしようとします。この活動の中にも翻訳は含まれています。

i18n WG は、@tdtsh さんや @sotayamashita さんのような workshopper やNode.jsに関連した記事の翻訳を行っている人が気軽に参加できるグループであるべきであり、それをサポートしない理由はないなと思っての今回の起票です。他の org でも同様の活動ができるのは重々承知ですが、新しい人を歓迎し、活動のサポートを積極的に行うのに、この team を利用するべきではないという理由はないように思います。実際 Slack の #translate チャンネルで似たような交流を行っていますが、ここでも歓迎するという話なので、あまり大きなことではないように感じます。

この提案を改めてまとめると、下記の2点が要点になります。
+ `nodejs/nodejs-ja` を、Node.js に関連する翻訳活動を行っている人たちが気軽に参加できる team とする
+ この repository を、Node.js に関連する翻訳のレビュワーを募集できる場所とする

文章がｺｯﾃﾘしちゃってすみません；
何かご意見などありましたら教えていただけると幸いです！ cc @nodejs/nodejs-ja

**Comment by yosuke-furukawa** [comment]
> 他の org でも同様の活動ができるのは重々承知ですが、新しい人を歓迎し、活動のサポートを積極的に行うのに、この team を利用するべきではないという理由はないように思います。実際 Slack の #translate チャンネルで似たような交流を行っていますが、ここでも歓迎するという話なので、あまり大きなことではないように感じます。

はい、個人的には translate のやり方を教える、translateの方法でベストプラクティスを伝えていくという所謂、「魚の釣り方を教えてあげる」「自転車に乗れない人の補助輪になってあげる」のには賛成です。その内容自体は i18n の WG でやっている活動を促進させるという意味で良いと思っています。

ここで言っていることが「Node.jsに関するあらゆる日本語翻訳のレビューを依頼する 1つのエンドポイントになる」というのと「Node.jsに関するあらゆる日本語翻訳のレビューはここで"一手に"引き受けます」と公言するのは印象が大きく違います。

前者なら賛成、後者なら反対です。

翻訳って時間と手間のかかる作業なので、なるべくであればリソースを集中させるよりも分散させてその熱量を持ったコミュニティで自治させるほうがうまく回る気がしています。

**Comment by sotayamashita** [comment]
> nodejs/nodejs-ja を、Node.js に関連する翻訳活動を行っている人たちが気軽に参加できる team とする

というのが翻訳活動をしている人たちが参加して互いに助け合ったりする team ということなら賛成です。こうすることで翻訳というところから node.js に興味を持ってくれる人が増えるのはとても良い気がします。

**Comment by watilde** [comment]
Slackで話してしまいましたが、基本的には前者です！そして、ただ引き受けるだけではなく、熱量がある人を見つけてはWGに誘うキッカケにしていき、翻訳活動をしている方たちを歓迎していければと思います :)

あまりに依頼が大量に来るようだったら方針を改めて考えていきましょう。こちらは、解決とさせてください。

**Comment by watilde** [comment]
Closing as resolved.
もし何か反対意見などありましたら、お気軽に再オープンしてください :)

**Comment by hiroppy** [comment]
slackのログ(https://iojs-jp.slack.com/archives/translate/p1488856935000102 から参照)
