### ISSUE TITLE
Request translation for Node.js User Survey promo copy

### ISSUE THREAD

**Issue by hackygolucky** [iojs/iojs-ja#121]
Hi! We'll be releasing the 2018 Node.js User Survey, and we'd love to have some promo copy in native languages to encourage our community users to participate. 

Requested copy to translate:
> Please take a few minutes to complete the 3rd annual Node.js User Survey, from the Node.js Foundation. Your participation helps us tell the story of Node.js and also informs Node.js Foundation strategy to ensure we invest in the right programs and resources to continue advancing Node.js. The results will be made public (find the most recent survey report here).
> 
> Thank you!

Thanks from the Node.js Foundation team!

**Comment by watilde** [comment]
I just tried, but I couldn't find a good sentence of `Your participation helps us tell the story of Node.js` in Japanese. Does anyone have any idea? @nodejs/nodejs-ja

> Node.js 財団は、第三回目となるユーザーアンケートを実施します。数分で終わる内容となっておりますので、ご協力お願い致します。`Your participation helps us tell the story of Node.js and` 集められたご意見・ご要望は、Node.js の継続的な成功を支えるための適切なプログラムの提供と、リソースの配分を最適化するために、Node.js 財団の戦略部門へと伝えられます。アンケートの結果は公開されます（最新の調査報告書はこちら）。

> 以上、よろしくお願いします。

Also, this translation^ would be too formal. Feedbacks are welcomed :)

**Comment by tdtsh** [comment]
I tried a little improvement. How about this?

> Node.js 財団は、第三回目となるユーザーアンケートを実施します。数分で終わる内容となっておりますので、ご協力お願い致します。集められたご意見・ご要望は Node.js の普及活動に役立てられると共に、 Node.js の継続的な成功を支えるための適切なプログラムの提供と、リソースの配分を最適化するために、Node.js 財団の戦略部門へも伝えられます。アンケートの結果は公開されます（最新の調査報告書はこちら）。

> ご協力をよろしくお願いします。

I was not feel like that was too formal, Except for the word of "以上".

**Comment by watilde** [comment]
LGTM!

We discussed at nodejs-ja slack and the above by @tdtsh is the result. @hackygolucky

**Comment by okuryu** [comment]
nit: `ともに` might be better than `共に`.
http://www.yamanouchi-yri.com/yrihp/techwrt-2-4s/t-2-4s03fa.htm

**Comment by hackygolucky** [comment]
Ah, y'all are the best, thanks!

**Comment by watilde** [comment]
closing as resolved.

**Comment by watilde** [comment]
I will remark, here is the translation.

```md
Node.js 財団は、第三回目となるユーザーアンケートを実施します。数分で終わる内容となっておりますので、ご協力お願い致します。集められたご意見・ご要望は Node.js の普及活動に役立てられるとともに、 Node.js の継続的な成功を支えるための適切なプログラムの提供と、リソースの配分を最適化するために、Node.js 財団の戦略部門へも伝えられます。アンケートの結果は公開されます（最新の調査報告書はこちら）。

ご協力をよろしくお願いします。
```
