### ISSUE TITLE
ウィークリーに日本でのio.js動向追加

### ISSUE THREAD

**Issue by kosamari** [iojs/iojs-ja#14]
基本的にio.js weeklyはgithub issueで情報収集 ->  mediumに投稿らしいので、なにかニュースに載せたい話題があれば /websiteの issuesで　'Evangelism: Weekly Update' のスレッドまで。
(今週分はこれ: https://github.com/iojs/website/issues/122)

**Comment by yosuke-furukawa** [comment]
Good.

**Comment by yosuke-furukawa** [comment]
@kosamari san, slackのinvitation っていってますでしょうか？？

**Comment by kosamari** [comment]
どうもinviteが来ないので今メールしましたー
