### ISSUE TITLE
Twitter パスワードの共有方法

### ISSUE THREAD

**Issue by shinnn** [iojs/iojs-ja#17]
現在は @kosamari さんと @shinnn がパスワードを所持しています。

**Comment by yosuke-furukawa** [comment]
一旦slackの private group作るのでそこで共有しておきましょうか。

**Comment by yosuke-furukawa** [comment]
はっ！これ共有してないですね。

**Comment by yosuke-furukawa** [comment]
共有できたので一旦 closeしちゃいます。
