### ISSUE TITLE
content以下の翻訳

### ISSUE THREAD

**Issue by yosuke-furukawa** [iojs/iojs-ja#18]
コンテント以下を翻訳していきたいと思っています。

[content/es6.md](https://github.com/iojs/iojs-ja/blob/master/content/es6.md) => @shinnn san
[content/faq.md](https://github.com/iojs/iojs-ja/blob/master/content/faq.md) => @kosamari san
[content/index.md](https://github.com/iojs/iojs-ja/blob/master/content/index.md) すごい少ないけど、、、 => @takashi san

という形でいかがでしょうか。こっちやりたいとかあれば教えて下さい。

**Comment by kosamari** [comment]
:+1:

**Comment by shinnn** [comment]
:ok_hand: もしほかに ES6 の翻訳を引き受けてくれる方がいましたら、是非。分担しましょう。

**Comment by yosuke-furukawa** [comment]
@shinnn  確かにちょっとおおいですね。一旦 @tgfjt さんと分担できるか相談して頂いてもいいですか？

**Comment by tgfjt** [comment]
@yosuke-furukawa  @shinnn 
各自やりやすい方式で良いと思いますが、
それぞれ WIP で PR を作って、TODO LIST を埋めていく とかだと手伝いやすいかもです！

**Comment by kosamari** [comment]
3つともマージされたのでcloseしますー

**Comment by yosuke-furukawa** [comment]
PR 中 https://github.com/iojs/website/pull/185
