### ISSUE TITLE
Where should we post Japanese-translated blog?

### ISSUE THREAD

**Issue by shinnn** [iojs/iojs-ja#2]
> Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.
- [Medium](https://medium.com/) (as [the original English blog](https://medium.com/@iojs) does)
- [Hatena blog](http://hatenablog.com/)
- [Tumblr](https://www.tumblr.com/)
- [Github pages](https://pages.github.com/)

Or else...

**Comment by yosuke-furukawa** [comment]
iojs.jpのドメインを持っているので、
iojs.jp/blogみたいな構造でGithub pagesから翻訳できると幸いです。

**Comment by e-jigsaw** [comment]
個人で gulp ベースの gh-pages 向けブログのシステムを作っている (https://github.com/jgsme/dev) ので、似たような機構のプロトタイプをサクッと作ってみました -> https://github.com/e-jigsaw/iojs.jp-blog

現在の `weekly/` 以下のページのプレビュー:
- http://e-jigsaw.github.io/iojs.jp-blog/2015-02-06.html
- http://e-jigsaw.github.io/iojs.jp-blog/io.js_and_node.js_Foundation.html

デザインは本家の Medium に寄せる形にしてみています。

もしよろしければ、適当な Github organization に移すなどして CNAME を置いて iojs.jp で公開できるといいなと考えているのですがいかがでしょうか...!また、公開までいけそうであればトップページを作ったり、自動デプロイの機構を整えたいなーとおもっております。

よろしくお願いします :bow:

**Comment by yosuke-furukawa** [comment]
+1、ちょっと考えます。

**Comment by e-jigsaw** [comment]
:ok_woman:

**Comment by yosuke-furukawa** [comment]
一旦決まったっぽいので close していきます。
