### ISSUE TITLE
Blog translation

### ISSUE THREAD

**Issue by shinnn** [iojs/iojs-ja#3]
- [x] [io.js Week of February 6th 2015](https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4)

(Related: #2)

**Comment by kosamari** [comment]
happy to take this one :)
行き先が#2で決まるまでgistにでも翻訳書いておきます。

**Comment by yosuke-furukawa** [comment]
一旦、iojs-cnと同じように、weeklyフォルダを立てて、そこに入れてもらってもいいかもしれませんね。

https://github.com/iojs/iojs-cn/tree/master/weekly

**Comment by kosamari** [comment]
ひとまず /weeklyに.mdで入れました
PR #10
