### ISSUE TITLE
PR merge ポリシー

### ISSUE THREAD

**Issue by kosamari** [iojs/iojs-ja#34]
Websiteワーキンググループのmeeting 見てたんですが、各言語コンテンツのPRの扱いにあたって(ワーキング・グループメンバーでは言語の壁でどうしていいか分からないので)　website repoに各ローカライゼーショングループからコラボレーターを追加しその人が直接マージできるようにするようです。
- コアコミッター広げた時も特に問題なかったし、どんどんコラボレーター増やして良いよね。
- 各言語コンテンツのPRをどうレビューするかは各チームに任せよう

みたいなことを話してました、のでPR のreview / merge　ルール設定の良い機会かなと。

現状のwebsite Repoでのルールはこちら。
https://github.com/iojs/website/blob/master/TRANSLATION.md
（現状ではPR出した人以外のネイティブ・スピーカーが :+1: 出せばmergeしてるそうです。）

**Comment by yosuke-furukawa** [comment]
いい機会ですね！
ちょっと考えていきましょう。
翻訳の品質はこのリポジトリの中で議論して、本家にp-rした時はそれが抜けもれなく追加されているかをチェックできればいいのかなと思っています。

**Comment by watilde** [comment]
こちら、website 側は `needs i18n +1` の label を付けて 👍  が出たら merge の運用で安定しましたね :)
解決ということで close します。
