### ISSUE TITLE
Twitter アカウント名について

### ISSUE THREAD

**Issue by shinnn** [iojs/iojs-ja#4]
他言語のi18n向けTwitterアカウントの多くが「iojs_*」という形式をとっています。
- https://twitter.com/iojs_ru
- https://twitter.com/iojs_cn
- https://twitter.com/iojs_ka
- https://twitter.com/iojs_pl

日本語版もそれに従って「iojs_jp」が望ましいと考えています。

しかしながら「iojs_jp」は[既に取得されているようです](https://twitter.com/iojs_jp)。アカウント作成日が`Sat Feb 07 23:47:08 +0000 2015`であることから、十中八九io.jsのローカライゼーションの動きを受けて作られたものかと思います。

アカウント作成者の方は #1 で書かれているとおりパスワードを @iojs/iojs-jp のメンバーに共有して頂けないでしょうか。

<del>アカウント名のスクワッティングではないことを祈ります。</del>

**Comment by kosamari** [comment]
US時間でTwitter見ていたらドドドっと他言語が新規アカウント取り出したので急いで@iojs_jp で取りました（passシェア済）clcose。

**Comment by shinnn** [comment]
@kosamari ありがとうございます。デフォルトアイコンのままだったので業者によるスクワッティングを疑っていました。申し訳ないです。

**Comment by shinnn** [comment]
もしかして https://twitter.com/iojs_ja の取得者も @kosamari さんですか？

もしできれば、本リポジトリの名前変更を受けて、twitter アカウント名も iojs_ja に変えたほうが良いかと思っています。まだ被リンクも少ないでしょうし、やるなら今のうちだと思います。

**Comment by kosamari** [comment]
_jaも_jpもパスワード同じです。
言語ローカライズという点で行くと_jaが正しいとは思うんですが、日本語はスペイン語とかポルトガル語と違って日本以外で使われてることが無いので_jpがユーザーからは解りやすいかなと思ったりもします。（なにかする時も.jpドメインと揃いますし、、、repoとずれるのはちょっと気持ち悪いですけど。）

翻訳コンテンツだけじゃなくてコミュニティのローカル情報も流してねっていう #1 とEvangelismチームを作る流れっぽいのでその場合JPのほうが良いかなと思ったり…むずかしいですが。

**Comment by shinnn** [comment]
> .jpドメインと揃う

これは利点ですね。

了解しました。変えなくていい方に +1 です。

**Comment by yosuke-furukawa** [comment]
変えなくて良いに +1 です。

**Comment by okuryu** [comment]
どちらでも良いと思います―。

**Comment by shinnn** [comment]
変えない、ということで再度 close します。
