### ISSUE TITLE
io.js Roadmap translation

### ISSUE THREAD

**Issue by yosuke-furukawa** [iojs/iojs-ja#41]
https://github.com/iojs/roadmap/issues/18

roadmap の翻訳が ready になりました！

**Comment by yosuke-furukawa** [comment]
https://github.com/iojs-jp/roadmap fork しました。
一旦ここで翻訳しましょうー！！

**Comment by yosuke-furukawa** [comment]
直接html編集するしかないかも。。。

**Comment by e-jigsaw** [comment]
slackにもpostしましたがちょっとやってみますー。

**Comment by yosuke-furukawa** [comment]
http://roadmap.iojs.jp/ DONE!!

Thanks @e-jigsaw .

**Comment by e-jigsaw** [comment]
:dancer:
