### ISSUE TITLE
io.jsウィークリー 2015/3/6

### ISSUE THREAD

**Issue by takashi** [iojs/iojs-ja#43]
https://github.com/iojs/evangelism/issues/16

**Comment by yosuke-furukawa** [comment]
https://github.com/iojs/evangelism/blob/master/weekly-updates/weekly-update.2015-03-06.md

**Comment by yosuke-furukawa** [comment]
出ましたね。

**Comment by e-jigsaw** [comment]
さっくり訳しますねー

**Comment by e-jigsaw** [comment]
#52

**Comment by e-jigsaw** [comment]
公開しましたー。 http://blog.iojs.jp/2015-03-06.html
