### ISSUE TITLE
iojs-ja の Node Foundation の移管是非

### ISSUE THREAD

**Issue by yosuke-furukawa** [iojs/iojs-ja#48]
mikealから 和解プロポーザルが出ていて、そこに iojs-ja も Node (io.js + node.js) project に移管するかどうかを voting で決めてほしいと言われているので、決めましょう。移管しても良ければチェックをお願いします。
- [x] @kosamari 
- [x] @shinnn 
- [x] @e-jigsaw 
- [x] @takashi 
- [x] @tgfjt 
- [x] @yosuke-furukawa

僕がここに書き忘れている方で意見がある方は是非 issue のコメント欄に +1 とか -1 とかをお書き下さい。

**Comment by e-jigsaw** [comment]
権限なくてチェック付けられないんですがチェックで問題ないです :+1:

**Comment by e-jigsaw** [comment]
ちなみに iojs.jp のドメインとかはどうされるんでしょう？

**Comment by takashi** [comment]
@e-jigsaw さんのものにチェックつけておきました :+1:

**Comment by e-jigsaw** [comment]
@takashi ありがとう〜

**Comment by yosuke-furukawa** [comment]
あれなんで権限ないんだろ

**Comment by yosuke-furukawa** [comment]
@kosamari さんが organization admin ですね。 @e-jigsaw さんの権限を付けて頂いてもいいでしょうか？

**Comment by kosamari** [comment]
@e-jigsaw さんiojs-jaチームメンバーのリストに入ってないです。以前もしかしてrepoのコラボレーターとかでした？　2週間くらい前に mikeal がgithub org の権限周り整理してたんですけど、その辺りで変わったのか・・・。
ちなみにチームメンバーは全員このrepoに対してAdmin権限になってるはずです。どなたかメンバー追加トライしてみて頂けないでしょうか。（i18nチーム個々にメンバー追加出来ないとしたら直さないといけないので）

（ちなみに私はmikealが他のチーム作るのを手伝ってる関係でiojs org全体のadminなのです）

**Comment by kosamari** [comment]
あと、iojs.jpと絡んで、どこまでがオフィシャルサイトの翻訳として含めるかWebsite WGで指標出してよってissueコメントしたんですけど今週のミーティングでは特に触れられなかったです（ひとまず`/content` の中身の扱いのみ）
デンマークチームも個別に同じようなこと（独自ドメインサイト作るか全部コンテンツはiojs.org/__ に入れるか）のissue立ててるんですけどそれもまだ結論出てないっぽい。

**Comment by e-jigsaw** [comment]
@kosamari 僕もともとコラボレータではないのでそもそも vote する必要なかったですかね？？

**Comment by kosamari** [comment]
@e-jigsaw いえいいえ、i18nチームは今のところメンバー追加になんのルールもなくて、https://github.com/iojs/website/issues/125 で手を上げていただくか、各チームごとに自由にメンバー追加できるんですが、今の私が権限だとなんでも出来過ぎて、逆にi18nチームメンバーのどなたかにメンバー追加試してみて欲しいなー。と（追加出来ない設定になっちゃってるならi18nチーム全体的に見なおさないといけないので。）。

**Comment by e-jigsaw** [comment]
あ、なるほど。じゃあ追加お待ちします

**Comment by yosuke-furukawa** [comment]
個別に追加だけしておきました。
ただ、iojs-jaチームではないので、 例えば、 @iojs/iojs-ja でメンションを飛ばしても反応できない可能性があるのではないかと思っています。

**Comment by kosamari** [comment]
@yosuke-furukawa https://github.com/orgs/iojs/teams/iojs-ja これって見れる・追加できますか？

**Comment by yosuke-furukawa** [comment]
@kosamari みれますけど、追加ができないですね。

**Comment by kosamari** [comment]
@e-jigsaw チームの方に追加しました。

**Comment by yosuke-furukawa** [comment]
@e-jigsaw iojs.jp のドメインとかは iojs.org と同じ運命を辿るかと思います。
ただどうなるかまだ全然わからないので、もうしばし待ちましょう。
ドメインは変わるかもしれないけど、コンテンツはそのまま生きると思います。

**Comment by tgfjt** [comment]
遅くなりましたが、チェックしました！
