### ISSUE TITLE
ウィークリー 3/20

### ISSUE THREAD

**Issue by e-jigsaw** [iojs/iojs-ja#62]
https://github.com/iojs/evangelism/issues/46
- [x] 翻訳
- [x] ブログ化
- [x] ツイート

**Comment by e-jigsaw** [comment]
PR: https://github.com/iojs/evangelism/pull/47

**Comment by yosuke-furukawa** [comment]
今回めっちゃ多いなー。

**Comment by e-jigsaw** [comment]
1.6.0 が多くてキツいすね

**Comment by e-jigsaw** [comment]
blog: http://blog.iojs.jp/2015-03-20.html
tweet: https://twitter.com/iojs_jp/status/580212868303314944
