### ISSUE TITLE
weekly updates 

### ISSUE THREAD

**Issue by yosuke-furukawa** [iojs/iojs-ja#75]
https://github.com/iojs/evangelism/pull/56

**Comment by yosuke-furukawa** [comment]
https://medium.com/node-js-javascript/io-js-week-of-april-10th-cbf6cf32409

**Comment by yosuke-furukawa** [comment]
@watilde さんにやってもらうことにしました。

**Comment by watilde** [comment]
完了です！
http://blog.iojs.jp/2015-04-10.html

**Comment by yosuke-furukawa** [comment]
Thanks mate!
