### ISSUE TITLE
Organizationの変更について

### ISSUE THREAD

**Issue by yosuke-furukawa** [iojs/iojs-ja#87]
気づいてないかもしれませんが、既にnodejs organizationに変わってます :dancer: 
今更何も問題ないかと思いますが、何かこの段階で問題があれば教えて下さい。
なければ思い思いの絵文字を入れておいてください :dancer:

**Comment by kosamari** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by nulltask** [comment]
:smile_cat:

**Comment by tgfjt** [comment]
おおー :tada:

**Comment by e-jigsaw** [comment]
:two_hearts:

**Comment by e-jigsaw** [comment]
iojs-jp もろもろどうするんでしたっけ

**Comment by yosuke-furukawa** [comment]
@e-jigsaw とりあえず、 io.js と node.js が完全に統合されるまではこのままです。
統合された後は nodejs-jp に変更が必要になると思います。

そして統合された後の問題は、僕らだけ blog.iojs.jp なんですよねぇ ... 
まぁnodejs.jp のメンテナンスをmesoさんから引き継ぐことにしようとおもっています。

**Comment by e-jigsaw** [comment]
なるほど〜
