### ISSUE TITLE
コミュニケーションツールについて

### ISSUE THREAD

**Issue by yosuke-furukawa** [iojs/iojs-ja#9]
ちょっとコミュニケーションツールを考えていて、iojs-jp.slack.comを作っており、そこで日本ユーザーグループとタイムリーなコミュニケーションが出来ればと思っているんですがいかがでしょうか。

それともgitterとかのほうが良ければそうします。

**Comment by kosamari** [comment]
ユーザーグループに合わせる形で良いのではないかと思います。

**Comment by yosuke-furukawa** [comment]
一旦お二人にslackのinvitationを送らせていただきました。

**Comment by takashi** [comment]
はじめまして、iojs-jpに参加させて頂きました @takashi と申します。
slackに招待いただければと思います。(まだ全体としてslackを使うか決まっていないようでしたら大丈夫です。)

**Comment by yosuke-furukawa** [comment]
送りましたー

**Comment by yosuke-furukawa** [comment]
翻訳したい人が他にもいればここも窓口として扱いたいので issue はオープンにしておきます。

**Comment by watilde** [comment]
READMEにSlack inのlinkがついたので、こちらもう閉じれますかね？

**Comment by hiroppy** [comment]
とじてよさそう
